print("começo hoje para me tornar o melhor programador do mundo")
print("vou me dedicar muito e nunca desistir")
print(7+4)
print("7"+"4")
print("Olá" , 5+4)
nome = input ("Qual é o seu nome?")
idade = input ("Quantos anos você tem?")
peso = input ("Qual o seu peso?")
hobby = input ("O que você mais gosta de fazer?")
print("Olá,", nome)